# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_timesta_cedd04_idx',
            old_name='analytics_a_timesta_3f7e23_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_action_cfeeae_idx',
            old_name='analytics_a_action_bf8912_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_univers_f34c52_idx',
            old_name='analytics_a_univers_94c7a8_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_admin_i_7a58b8_idx',
            old_name='analytics_a_admin_i_7e2fa1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_entity__9ea020_idx',
            old_name='analytics_a_entity__6f0a94_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='analytics_a_univers_19056f_idx',
            old_name='analytics_a_univers_8d3c5e_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionevent',
            new_name='analytics_i_created_ce8979_idx',
            old_name='analytics_i_created_c9f8f0_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionevent',
            new_name='analytics_i_event_t_563995_idx',
            old_name='analytics_i_event_t_85a639_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionevent',
            new_name='analytics_i_univers_f39448_idx',
            old_name='analytics_i_univers_0baf43_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionevent',
            new_name='analytics_i_user_id_3cf8e0_idx',
            old_name='analytics_i_user_id_982a4d_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionevent',
            new_name='analytics_i_entity__5696ed_idx',
            old_name='analytics_i_entity__ad0d3d_idx',
        ),
        migrations.RenameIndex(
            model_name='interactionevent',
            new_name='analytics_i_univers_45c6c4_idx',
            old_name='analytics_i_univers_a7b245_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('opportunity', 'Opportunity'), ('user', 'User'), ('skill', 'Skill'), ('match', 'Match'), ('profile', 'Profile'), ('settings', 'Settings'), ('report', 'Report'), ('knowledge', 'Knowledge'), ('career_role', 'Career Role'), ('notification', 'Notification')], help_text='Type of entity affected', max_length=50),
        ),
        migrations.AlterField(
            model_name='interactionevent',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('opportunity', 'Opportunity'), ('user', 'User'), ('skill', 'Skill'), ('match', 'Match'), ('profile', 'Profile'), ('dashboard', 'Dashboard'), ('page', 'Page'), ('knowledge', 'Knowledge'), ('subscription', 'Subscription'), ('notification', 'Notification')], help_text='Type of entity involved in the event', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='interactionevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('search', 'Search'), ('save', 'Save'), ('unsave', 'Unsave'), ('apply', 'Apply'), ('share', 'Share'), ('filter', 'Filter'), ('sort', 'Sort'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('knowledge_search', 'Knowledge Search'), ('knowledge_open', 'Knowledge Open'), ('knowledge_no_answer', 'Knowledge No Answer'), ('opportunity_open', 'Opportunity Open'), ('opportunity_save', 'Opportunity Save'), ('career_gps_open', 'Career GPS Open'), ('subscription_created', 'Subscription Created')], db_index=True, help_text='Type of interaction event', max_length=50),
        ),
    ]
