# Generated by Django 5.0.1 on 2026-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_a_timesta_3f7e23_idx_analytics_a_timesta_cedd04_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionevent',
            name='event_type',
            field=models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('search', 'Search'), ('save', 'Save'), ('unsave', 'Unsave'), ('apply', 'Apply'), ('share', 'Share'), ('filter', 'Filter'), ('sort', 'Sort'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('signup', 'Signup'), ('knowledge_search', 'Knowledge Search'), ('knowledge_open', 'Knowledge Open'), ('knowledge_no_answer', 'Knowledge No Answer'), ('opportunity_open', 'Opportunity Open'), ('opportunity_save', 'Opportunity Save'), ('career_gps_open', 'Открытие карьерного навигатора'), ('subscription_created', 'Subscription Created')], db_index=True, help_text='Type of interaction event', max_length=50),
        ),
    ]
