# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='careerrole',
            new_name='careers_car_univers_e027d0_idx',
            old_name='careers_car_univer_1d12a7_idx',
        ),
        migrations.RenameIndex(
            model_name='careerrole',
            new_name='careers_car_active_031383_idx',
            old_name='careers_car_active_31df9e_idx',
        ),
        migrations.RenameIndex(
            model_name='careerroleskill',
            new_name='careers_car_career__e68367_idx',
            old_name='careers_car_career_06c20c_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='careers_ski_univers_9a9842_idx',
            old_name='careers_ski_univer_61b124_idx',
        ),
        migrations.RenameIndex(
            model_name='skill',
            new_name='careers_ski_name_93b60f_idx',
            old_name='careers_ski_name_127c41_idx',
        ),
        migrations.RenameIndex(
            model_name='studentskill',
            new_name='careers_stu_student_e57e23_idx',
            old_name='careers_stu_student_03f4c4_idx',
        ),
        migrations.RenameIndex(
            model_name='studentskill',
            new_name='careers_stu_skill_i_997be9_idx',
            old_name='careers_stu_skill_i_c167dd_idx',
        ),
        migrations.RenameIndex(
            model_name='studentskill',
            new_name='careers_stu_verifie_4a8f2a_idx',
            old_name='careers_stu_verifie_d4f75f_idx',
        ),
    ]
