# Generated by Django 5.0.1 on 2026-09-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_rename_careers_car_univer_1d12a7_idx_careers_car_univers_e027d0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerrole',
            name='avg_salary',
            field=models.CharField(blank=True, help_text='Free-text salary range shown to students, e.g. "120 000 - 180 000 ₽"', max_length=120),
        ),
        migrations.AddField(
            model_name='careerrole',
            name='demand_level',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='careerrole',
            name='education_path',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of steps students can take toward this role'),
        ),
    ]
