# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_ae6ed6_idx',
            old_name='notificatio_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_student_8adac3_idx',
            old_name='notificatio_student_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_status_9a4505_idx',
            old_name='notificatio_status_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('simulated', 'Simulated'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', help_text='Current notification status', max_length=10, verbose_name='Status'),
        ),
    ]
