# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='profiles_st_univers_6194d6_idx',
            old_name='profiles_st_univers_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='profiles_st_onboard_133df4_idx',
            old_name='profiles_st_onboard_idx',
        ),
    ]
