# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_k_univers_ab3bb7_idx',
            old_name='knowledge_kn_univers_a8b9f7_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_k_univers_b5c9c2_idx',
            old_name='knowledge_kn_univers_e8c9d5_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_k_verifie_1aa80c_idx',
            old_name='knowledge_kn_verifie_b7a3c4_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_k_actual__682991_idx',
            old_name='knowledge_kn_actual__c6d8e2_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgeitem',
            new_name='knowledge_k_created_c7849e_idx',
            old_name='knowledge_kn_created_f9e1a5_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgereport',
            new_name='knowledge_k_univers_074ba5_idx',
            old_name='knowledge_kn_univers_d4f2b8_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgereport',
            new_name='knowledge_k_status_46e5cf_idx',
            old_name='knowledge_kn_status_e3c7a9_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgereport',
            new_name='knowledge_k_knowled_1ead04_idx',
            old_name='knowledge_kn_knowled_a5d9f1_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgereport',
            new_name='knowledge_k_created_dba969_idx',
            old_name='knowledge_kn_created_b8e2c6_idx',
        ),
    ]
