# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_student_f0e247_idx',
            old_name='subscriptio_student_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_topic_b00d34_idx',
            old_name='subscriptio_topic_idx',
        ),
    ]
