# Generated by Django 5.0.1 on 2026-09-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchresult',
            new_name='opportuniti_student_fce60e_idx',
            old_name='opportuniti_student_score_idx',
        ),
        migrations.RenameIndex(
            model_name='matchresult',
            new_name='opportuniti_opportu_0058bd_idx',
            old_name='opportuniti_opportu_idx',
        ),
        migrations.RenameIndex(
            model_name='matchresult',
            new_name='opportuniti_calcula_4e436f_idx',
            old_name='opportuniti_calcula_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_created_1b69e8_idx',
            old_name='opportuniti_created_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_univers_fccc4f_idx',
            old_name='opportuniti_univers_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='opportuniti_publish_cafe68_idx',
            old_name='opportuniti_publish_idx',
        ),
        migrations.RenameIndex(
            model_name='savedopportunity',
            new_name='opportuniti_student_a92dc1_idx',
            old_name='opportuniti_student_idx',
        ),
    ]
